server:
  port: 8090

spring:

  data-source:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      product-validation-success: product-validation-success
      product-validation-fail: product-validation-fail
      orchestrator: orchestrator
    consumer:
      group-id: product-group
      auto-offset-reset: latest

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: OFF
