server:
  port: 8090

spring:
  data-source:
    driver-class-name: org.postgresql.Driver
    url: jdb:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/{$DB_NAME:product-db}
    username: ${DB:USER:postgres}
    password: ${DB:PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect